app/models.py
# coding=utf-8
from peewee import *
import datetime
from flask_login import UserMixin
from . import login_manager
import os
from config import BASE_DIR


db = SqliteDatabase(BASE_DIR+'/sqlite.db')

class BaseModel(Model):
    class Meta:
        database = db

class User(UserMixin,BaseModel):

    username = CharField()
    access_token = CharField(null=True)
    power = BooleanField(default=False)
    avatar = CharField(null=True)
    grade = CharField(null=True)


    def to_json(self):
        json_data = {
            'id':self.id,
            'name':self.username,
            'power':self.power,
            'avatar':self.avatar if self.avatar else "",
            'grade':self.grade
        }
        return json_data

    def __repr__(self):
        return '<小组成员 %s>' % (self.username)

    def is_superuser(self):
        return True if self.power else False


class AnonymousUser():
    @property
    def is_anonymous(self):
        return True

@login_manager.user_loader
def load_user(user_id):
    return User.select().where(User.id == int(user_id)).first()

class Interviewer(BaseModel):
    name = CharField(max_length=128)
    grade = SmallIntegerField() #几年级
    stu_num = CharField(max_length=16)
    classes = CharField(max_length=5) #20××年面试
    sex = BooleanField(default=True) #True为男
    is_alive = BooleanField(default=False,help_text='是否面试')

    def to_json(self):
        json_data = {
            'id':self.id,
            'name':self.name,
            'sex':self.sex,
            'num':self.stu_num,
            'grade':self.grade,
            'classes':self.classes,
        }
        return json_data

    def __repr__(self):
        return '<面试者  %s>' % (self.name)

class Record(BaseModel):
    interviewer = ForeignKeyField(Interviewer)
    data = DateTimeField(default=datetime.datetime.now)
    is_power = BooleanField(default=False,help_text='大轮综合评定')
    big_num = CharField(help_text='大轮数')
    sml_num = SmallIntegerField(help_text='小轮数',null=True)
    good = TextField(help_text='优点',null=True)
    bad = TextField(help_text='缺点',null=True)
    score = SmallIntegerField(help_text='90-100:SS、80-89:S、70-79:A、60-69:B、50-59:C、50以下:D') #评分
    leader = ForeignKeyField(User)
    others = TextField(help_text='组员，保存id序列',null=True)

    def to_json(self):
        others = ''
        for i in self.othres.split():
            u = User.select().where(id=int(i)).first()
            others = others + '??? ' if not u else u.username+' '
        json_data = {
            'owner':self.interviewer.name,
            'time':self.data,
            'power':self.is_power,
            'big':self.big_num,
            'sml':self.sml_num,
            'good':self.good,
            'bad':self.bad,
            'score':self.score,
            'leader':self.leader.username,
            'others':others
        }
        return json_data

app/__init__.py
# coding=utf-8
from flask import Flask
from config import config
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.index'
#登陆提示信息
login_manager.login_message=u'对不起，您还没有登录'
login_manager.login_message_category='info'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    login_manager.init_app(app)

    # 附加基本路由
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # 附加通用api路由
    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api')

    # 附加权限验证路由
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='')

    return app

app/admin/views.py
from flask_admin import BaseView,expose
from flask_login import current_user
import requests,json
from app.models import User

class Setting(BaseView):
    @expose('/')
    def index(self):
        now_user = User.select().count()
        max_user = requests.get('https://api.xiyoulinux.org/users?'+
                                'access_token='+current_user.access_token+
                                '&per_page=1')
        total = json.loads(max_user.text)['total_count']
        if total>now_user:
            self.flash_user()
        return self.render('admin/setting.html')


    @staticmethod
    def flash_user():
        url = 'https://api.xiyoulinux.org/users?access_token=%s&per_page=%d'
        h = requests.get(url%(current_user.access_token,1))
        total = json.loads(h.text)['total_count']
        h = requests.get(url%(current_user.access_token,total))
        user = json.loads(h.text)['data']
        for i in  user:
            if not User.select().where(User.id==i['id']).first():
                print(i['id'])
                User.create(id=i['id'], username=i['name'],
                            avatar=i['avatar_url'], grade=i['grade'])

app/api/__init__.py
#coding=utf-8
from flask import Blueprint

api = Blueprint('api',__name__)

from . import views

app/api/views.py
#coding=utf-8
from . import api
from flask import current_app,jsonify,request
import json,datetime
from app.models import Interviewer,Record


@api.route('/signin', methods=['GET'])
def get_signin_list():
    s = current_app.config['WAIT_LIST']
    lists = []
    for i in s:
        lists.append((i.id,i.name,))
    data = {
        'total': len(s),
        'data': lists,
    }
    return jsonify(data)


@api.route('/signin', methods=['POST'])
def add_signin():
    stu_num = request.json.get('stu_num')
    inter = Interviewer.select().where(Interviewer.classes == str(datetime.datetime.now().year) and
                               Interviewer.stu_num == stu_num).first()
    if inter: #学号正确
        if inter not in current_app.config['WAIT_LIST']: #不在等待队列
            if not Record.select().where(Record.interviewer == inter and
                   Record.big_num == current_app.config['NOW_TIMES']).first():
                current_app.config['WAIT_LIST'].append(inter)
                status = True
                msg = '签到成功'

            else:
                status = False
                msg = '已参加过本轮面试，无需重复签到'
        else:
            status = False
            msg = '已在等待队列'
    else:
        status = False
        msg = '没有找到对应的应聘者'

    return jsonify({'msg':msg,'status':status})

@api.route('/interviewer')
def interviewer():
    stu_num = request.args.get('stu_num')
    inter = Interviewer.select().where(Interviewer.stu_num == stu_num and
                               Interviewer.classes == datetime.datetime.now().year).first()
    if inter:
        return jsonify({'status':True,'data':inter.to_json()})
    else:
        return jsonify({'msg':'找不到信息','status':False})

app/main/__init__.py
#coidng=utf-8
import requests, json
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

#获取到用户的access token
def Get_AccessToken(authcode):
    url = 'https://sso.xiyoulinux.org/oauth/access_token'
    data = {
        'grant_type':'authorization_code',
        'client_id':'spider',
        'client_secret':'$2y$10$OmNWVGJLqsCAbHELzg4VwezzT/94Jpn3J',
        'code':authcode,
        'redirect_uri':'http://localhost:8080/login/'
    }
    try:
        html = requests.post(url,data=data)
        js = json.loads(html.text)
        at = js.get('access_token')
        ei = js.get('expires_in')
        return (at,ei)
    except Exception as e:
        print(e)
    return (None,None)

#获取用户信息
def Get_User_message(access_token):
    url = 'https://api.xiyoulinux.org/me?access_token=%s' % access_token
    html = requests.get(url)
    user = json.loads(html.text)
    return user

app/main/views.py
#coding=utf-8
from . import main
from flask import render_template,current_app,redirect
from app.auth.views import Get_Auth
from flask_login import login_required,current_user


@main.route('/secret')
@login_required
def secret():
    return 'Only authenticated users are allowed!'


@main.route('/')
def index():
    return render_template('base.html')


@main.route('/login')
def login():
    return redirect(Get_Auth())


@main.route('/sign_in')
@login_required
def sign_in():
    return render_template('sign_in.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="/admin/static/bootstrap/bootstrap3/swatch/default/bootstrap.min.css?v=3.3.5" rel="stylesheet">
    {% block headscript %}{% endblock %}
</head>
<body>
{% if current_user.is_anonymous %}
    请<a href="{{ url_for('main.login') }}">登录</a>
{% else %}
    欢迎<a href="">{{ current_user.username }}</a>
    {% if current_user.power %}
        <a href="/admin">进入后台</a>
    {% endif %}
    <a href="{{ url_for('auth.logout') }}">退出登录</a>
{% endif %}
{% block body %}
<a href="{{ url_for('main.sign_in') }}">打卡签到</a>
<a>我要开面</a>
{% endblock %}
</body>
{% block tailscript %}{% endblock %}
    <script src="/admin/static/vendor/jquery.min.js?v=2.1.4" type="text/javascript"></script>
    <script src="/admin/static/bootstrap/bootstrap3/js/bootstrap.min.js?v=3.3.5" type="text/javascript"></script>
<!--
 background:City-Zero
 front end:special-wen
 -->
</html>

app/templates/sign_in.html
{% extends 'base.html' %}
{% block body %}
    学号：<input type="text" id="stu_num" onblur="stu_msg()">
    <button id="submit" onclick="sub()">提交</button>
    <div id="stu_msg"></div>
{% endblock %}

{% block tailscript %}
<script>
function stu_msg() {
    let xhr = new XMLHttpRequest();
    let stu_num = document.getElementById('stu_num');
    let stu_msg = document.getElementById('stu_msg');
    let data = {"stu_num":stu_num.value};
    xhr.onreadystatechange = function () {
        if(xhr.readyState == 4 && xhr.status==200){
            let json = JSON.parse(xhr.responseText);
            if(json.status){
                stu_msg.innerText="";
                stu_msg.innerText = xhr.responseText;
            }
        }
    };
    xhr.open('GET','{{ url_for('api.interviewer') }}?stu_num='+stu_num.value);
    xhr.send();
}

function sub() {
    let xhr = new XMLHttpRequest();
    let stu_num = document.getElementById('stu_num');
    let data = {"stu_num":stu_num.value};
    xhr.onreadystatechange = function () {
        if(xhr.status == 200 && xhr.readyState == 4){
            let json = JSON.parse(xhr.responseText);
            if(json.status == true){
                alert(json.msg);
            }else{
                alert(json.msg);
            }
        }
    };
    xhr.open('POST','{{ url_for('api.add_signin') }}');
    xhr.setRequestHeader("Content-Type",'application/json;charset=utf-8');
    xhr.send(JSON.stringify(data));
}
</script>
{% endblock %}